language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python mhapsite/manage.py makemigrations
- python mhapsite/manage.py migrate
- python mhapsite/manage.py loaddata ./fixtures/quotes.json
- python mhapsite/manage.py test
env:
  global:
    secure: N2GP6W6vcOd/d1ideJCbl8oi2PeUV41ET643gTQw3oLj1XHHHDkoJm6s68vr6MPMtOgjtjdJwLWAySMS7mi6XnNZck+TKrB3sZ4rLQ6ebTljYqV12CyOAbaVI7via1s9P6ZW4qOkcQpcvFy9QjMi5rvrnAph4sMnl+luBfmKZcSzHMpL18xlWC5XVTiADZUL3j3A+iyHbxf9p9t5JgSJ4lUhzz7b4XH+RA956jW9xVX6YLGunt8eR0cuNbRdRClnGF2qg41tnjKW+QfOy5xmlBCDxe2tTmsstHTAHP3BbkQQbzTr5SaWq591vtRu7yWuKdBY+G8QsCPZ0fg6aWcADIYK7KWDc13fwqQ8dCA0anEZCPCO+MLCqcb0ecuqYErZzGNlbncl31IaP1GVv6sSGpqYFqIdBPkQK4oCQTf7ch4czhQ9qL95OKgC2D5MFaNOc6l1Wjs0SchiBe1EzP2bUtsCp0tWv4QMtrTWj6iWx5b2WGhuy41JVy7/SQe21hFNTTPmNk8QLfWp2JTmpVL7H53CuOHv2dngJajtKXcKq+Bg5fNVYU8v01rU+Dlw7ZlVYjYWTFHAo8QgbV+jUA1wn0KIp7QJfN5rQXTM+Q/QfvXgZtsV6IG8Zpd19jE3poc08YTLloVllTwTK+I/WYXAgNwhleqIpatYIio3o+ytAFA=
