language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python mhapsite/manage.py makemigrations
- python mhapsite/manage.py migrate
- python mhapsite/manage.py loaddata ./fixtures/quotes.json
- python mhapsite/manage.py test mhap
env:
  matrix:
    secure: FSvW3ISjHxHX4v4bP+BCDjn7NMSpL+6Z4D9fVDgUs1r8Griu1FzS9yxupyv8m2OBsveKk4wiTMMf9DS6K+JEBPU8jF/IY5YU2nwy0gVwggpV0VcfGUv4iZFVuMd93k05CgPrDHTlQULb2mnnqU3JYsKMIkHWaQGGs5SirTAz9MDK/1e2Ga0YcxNwivo+r0XDnDkmcAzV/1sOX20FfRXZBj4zqA6Mul2sZhErZbTX5cqqHbcCpdzfbW9eqzOAO+1CcmGVmyVLcY8XbbZgqyQp99MhW/6tZCYLYaWvbaw4QLp6lKzrfoNY3PTx6oeJeiGY6s95807GGnG49fnv3J7kd0A1vUKR7EapXUnMRzXzKtsGLjQrTqgv6QKM23Qyg/wgfV8zoY0oCAyvkmQQ1BX/Y+RLgjETWiVOoYUt6ZBSDaWMQxTAjQy4J9rE+qaZfqSxdScQnYfnVRlH3+hWhSgllIdnz3iNqV7nkJQQ3fi1VzE5WQms+qa1R+QRDW+joLIWGuj1LEOv2UZkuCaRsoYWF/57+GWdPeXEkV0GQLG3XLXJEa2hwfoFVs60bfKFqEshUoLmQ8M3HakCpiwG/0mzvdigkm5+Wdtgw70eFPJ7GBZdtD8FA4W9HJ8eABZzsjRfB9RJ4EwKbz9okomtJAdkFGKj8A1HhTenhDCNayqa6eQ=
