language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- rm db.sqlite3
- python mhapsite/manage.py makemigrations
- python mhapsite/manage.py migrate
- python mhapsite/manage.py loaddata ../fixtures/quotes.json
- python mhapsite/manage.py test
env:
  matrix:
    secure: LilN6j6lRHk35ioElULz7T3h8qIBLusHn970fRfzlm0xI/dBTUrmccYaO0hLLVpSvSpP571zk6SUgmHVgN5N6qmKRQVgkqsddSKOODHXMWv7Hh1Emy8/fzZ+dzmkHp2Imx7RR8jNEBOKfjlmRf405oHI9z9Orc4W00J+QaHwtyWlyjYXfzGCqq/0EDbmvXtqXqUlZETbRW3VPQ60ed1bZXFvOIrFGLn3zvvmd5fmr7b1UZizMn/vxYsaOdSyunwxJvR+VgxmwDmxnTn69CzYAfa0ka7LGbzcu0+AswlAY8ykT4zwuqEojwnnFPSIG/NaA/T9wDcA3XfphAgXv2rLoCl/eE3zcXn/0wx6B9/eWgPXgO18Lc8YbfBIykASPuC9RwLthUDZDHhkHds4tDAnyZYzd+rB4x4+EEdQW+JPj58L2ckwjWOi0zQ3RvfxwO5wQZnopu9hmAXCciWpqy2tFKnh1a6Ctd4uk8hvH+M/I0R4C8Ex7e0DqQJDlv/G/LwVmDyFfPChSqO2VgjF+6/qUqcLgc4ayXiAx56m3GTeRoP33lTqEsfpatjAdkx93+NctOCBrbIE52E0fXiP5BZcpHBTC0v2P9JJV97+oBd+k6HrRdEyiuoBNF7J966e/74riNlng2xjftSrizAa0Q9U+Mb1G4kCzL7Yfa9zy1Q/TYY=
