# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('birth_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to=settings.AUTH_USER_MODEL)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emailID', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
