# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
