# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0002_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='NULL', unique=True),
        ),
    ]
