# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0003_auto_20170228_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='secret',
            field=models.BooleanField(default=True),
        ),
    ]
