# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0003_auto_20170402_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
