# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0004_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='l',
            field=models.BooleanField(default=True),
        ),
    ]
