# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0004_auto_20170228_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
