# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0004_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
