# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhap', '0005_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seems_depressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='seems_suicidal',
            field=models.BooleanField(default=False),
        ),
    ]
